language: python

cache: pip

python:
  - "3.5"
  - "3.6"

install:
  - sudo apt-get update
  - pip install -r requirements-dev.txt
  - pip install .
  
  # Show all packages, for debugging

script: 
  - python setup.py test

after_success:
  - coveralls
